In [3]:
import numpy as np 

In [7]:
a = np.array([1,2,3])  
print (a)
print("===================")
b = np.array([[1,  2],  [3,  4]])  
print (b)

[1 2 3]
[[1 2]
 [3 4]]


In [10]:
# 将数据类型应用于 ndarray 对象
#先创建了数据类型
dt = np.dtype([('age',np.int8)]) 
#创建ndArray的时候使用该数据类型
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(a)
print(a.dtype)

[(10,) (20,) (30,)]
[('age', 'i1')]


In [12]:
# 下面的示例定义一个结构化数据类型 student，包含字符串字段 name，整数字段 age，及浮点字段 marks，并将这个 dtype 应用到 ndarray 对象。
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print(a)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


In [25]:
a = np.array([[1,2,3],[4,5,6]])  
print(a.shape)
print(a)
print("------------------")
b = a.reshape(3,2)
print(b.shape)
print(b)
print("------------------")
print (b.itemsize) # 数组元素数量，也即是 行*列

(2, 3)
[[1 2 3]
 [4 5 6]]
------------------
(3, 2)
[[1 2]
 [3 4]
 [5 6]]
------------------
4


In [45]:
x = np.empty([3,2], dtype = int) 
print (x)
# 注意 − 数组元素为随机值，因为它们未初始化。

[[ 1690800896         710]
 [          0           0]
 [          1 -2147483648]]


In [48]:
# 创建指定大小的数组，数组元素以 0 来填充：
# 默认为浮点数
x = np.zeros(5) 
print(x)
 
# 设置类型为整数
y = np.zeros((5,), dtype = np.int) 
print(y)
 
# 自定义类型
z = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(z)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [51]:
# 默认为浮点数
x = np.ones(5) 
print(x)

# 自定义类型
x = np.ones([2,2], dtype = int)
print(x)

[1. 1. 1. 1. 1.]
[[1 1]
 [1 1]]


In [58]:
x =  [1,2,3] #列表转array
y =  (1,2,3) #元组转array
z =  [(1,2,3),(4,5)]  #元组列表转array
a = np.asarray(z)  
print (a)

[(1, 2, 3) (4, 5)]


In [70]:
# numpy.linspace 函数用于创建一个一维数组，数组是一个等差数列构成的，格式如下：
# 以下实例用到三个参数，设置起始点为 1 ，终止点为 10，数列个数为 10。
a = np.linspace(1,10,10)
print(a)
a = np.linspace(1,1,10)
print(a)
#  不包括终止值
a = np.linspace(10, 20,  5, endpoint =  False)  
print(a)
print("===================")
a =np.linspace(1,10,10,retstep= True)
print(a)
print("----------------------")
# 拓展例子
b =np.linspace(1,10,10).reshape([10,1])
print(b)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[10. 12. 14. 16. 18.]
(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)
----------------------
[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]


In [73]:
# numpy.logspace 函数用于创建一个于等比数列。格式如下：
# 默认底数是 10
a = np.logspace(1.0,  2.0, num =  10)  
print (a)
print("================================")
# 将对数的底数设置为 2 :
a = np.logspace(0,9,10,base=2)
print (a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]
[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


In [75]:
# NumPy 切片和索引

In [78]:
a = np.arange(10)
print(a)
s = slice(2,7,2)   # 从索引 2 开始到索引 7 停止，间隔为2
print (a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [80]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
# 从某个索引处开始切割
print('从数组索引 a[1:] 处开始切割')
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
从数组索引 a[1:] 处开始切割
[[3 4 5]
 [4 5 6]]


In [81]:
# 切片还可以包括省略号 …，来使选择元组的长度与数组的维度相同。 如果在行位置使用省略号，它将返回包含行中元素的 ndarray。
a = np.array([[1,2,3],[3,4,5],[4,5,6]])  
print (a[...,1])   # 第2列元素
print (a[1,...])   # 第2行元素
print (a[...,1:])  # 第2列及剩下的所有元素

[2 4 5]
[3 4 5]
[[2 3]
 [4 5]
 [5 6]]
